## name: Tokyo Night
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_night.conf

font_family CaskaydiaMono Nerd Font
include colors.conf
window_padding_width 10 
allow_remote_control yes
listen_on unix:/tmp/kitty
background_blur 1
background_opacity 0.90

# Map Super+C/V/X to clipboard actions inside kitty
map super+c copy_to_clipboard
map super+v paste_from_clipboard
# For cut: map to send ctrl+x to the running program (so editors will cut)
map super+x send_text all \x18
cursor_trail 1
