theme = "yours"
hide_quick_activation = true

[[providers.prefixes]]
prefix = "$"
provider = "bluetooth"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "."
provider = "symbols"


bluetooth = [
  { action = "find", bind = "ctrl f", after = "AsyncClearReload" },
  { action = "remove", bind = "ctrl d", after = "AsyncReload" },
  { action = "trust", bind = "ctrl t", after = "AsyncReload" },
  { action = "untrust", bind = "ctrl t", after = "AsyncReload" },
  { action = "pair", bind = "Return", after = "AsyncReload" },
  { action = "connect", default = true, bind = "Return", after = "AsyncReload" },
  { action = "disconnect", default = true, bind = "Return", after = "AsyncReload" },
]
